/* =====================================================
   MAKHASWA HOLDINGS — SHARED COMPONENTS
   DRY: Reusable header, footer, and <head> meta.
   Single source of truth for site-wide navigation,
   contact info, and branding.
   ===================================================== */

/**
 * Site-wide configuration — Single source of truth.
 * Update company info, nav links, or contact details
 * here and every page updates automatically.
 */
const SITE_CONFIG = {
    company: {
        name: 'Makhaswa',
        legalName: 'Holdings (Pty) Ltd',
        registration: 'K2017/307900/07',
        bbbee: 'B-BBEE Level 1 Contributor',
        tagline: 'A dynamic civil engineering and construction company committed to excellence, efficiency, and building lasting infrastructure solutions across South Africa.',
        logoSrc: 'images/transparent-logo.png',
        logoAlt: 'Makhaswa Holdings Logo',
        copyright: `\u00A9 ${new Date().getFullYear()} Makhaswa Holdings (Pty) Ltd. All Rights Reserved.`
    },

    nav: [
        { label: 'Home', href: 'index.html' },
        { label: 'About Us', href: 'about.html' },
        { label: 'Services', href: 'services.html' },
        { label: 'Projects', href: 'index.html#projects' },
        { label: 'Careers', href: 'careers.html' },
        { label: 'Contact', href: 'contact.html' },
    ],

    quickLinks: [
        { label: 'Home', href: 'index.html' },
        { label: 'About Us', href: 'about.html' },
        { label: 'Our Services', href: 'services.html' },
        { label: 'Projects', href: 'index.html#projects' },
        { label: 'Careers', href: 'careers.html' },
        { label: 'Contact Us', href: 'contact.html' },
        { label: 'FAQs', href: 'faq.html' },
        { label: 'Terms & Conditions', href: 'terms.html' },
    ],

    capabilities: [
        'Earthworks',
        'Civil Works',
        'Road Construction',
        'General Building',
        'Project Management',
    ],

    offices: {
        pretoria: {
            label: 'Pretoria',
            address: '869 Patryshond Street, Garsfontein, Pretoria, Gauteng, 0042, South Africa',
            phone: '012 944 1702',
            mapQuery: '869%20Patryshond%20Street%2C%20Garsfontein%20Pretoria',
            mapTitle: 'Garsfontein Office',
            mapLabel: 'Garsfontein \u2013 869 Patryshond Street',
        },
        johannesburg: {
            label: 'Johannesburg',
            address: 'Riversands Incubation Hub, Midrand, 2021',
            phone: '011 568 0938',
            mapQuery: 'Riversands%20Incubation%20Hub',
            mapTitle: 'Midrand Office',
            mapLabel: 'Midrand \u2013 Riversands Incubation Hub',
        },
    },

    contact: {
        whatsapp: '+27 81 359 8003',
        emails: [
            'info@makhaswaholdings.co.za',
            'admin@makhaswaholdings.co.za',
            'tenders@makhaswaholdings.co.za',
        ],
    },
};


/* =====================================================
   HELPER: Determine the active page from the filename
   ===================================================== */
function getActivePage() {
    const path = window.location.pathname;
    const filename = path.substring(path.lastIndexOf('/') + 1) || 'index.html';
    return filename;
}


/* =====================================================
   BUILD HEADER HTML
   ===================================================== */
function buildHeader() {
    const activePage = getActivePage();
    const cfg = SITE_CONFIG;

    const navLinksDesktop = cfg.nav.map(link => {
        const isActive = activePage === link.href || (activePage === '' && link.href === 'index.html');
        return `<a href="${link.href}"${isActive ? ' class="active"' : ''}>${link.label}</a>`;
    }).join('\n            ');

    const navLinksMobile = cfg.nav.map(link =>
        `<a href="${link.href}">${link.label}</a>`
    ).join('\n        ');

    return `
    <!-- =====================================================
         HEADER (Auto-generated by components.js)
    ===================================================== -->
    <header>
        <a href="index.html" class="logo">
            <img src="${cfg.company.logoSrc}" alt="${cfg.company.logoAlt}">
            <div class="logo-text">${cfg.company.name}<small>${cfg.company.legalName}</small></div>
        </a>

        <!-- Desktop Navigation -->
        <nav id="desktop-nav">
            ${navLinksDesktop}
        </nav>

        <!-- Burger Button -->
        <button class="burger" id="burger-btn" aria-label="Toggle menu" aria-expanded="false">
            <i data-lucide="menu" width="26" height="26"></i>
        </button>
    </header>

    <!-- Mobile Navigation Drawer -->
    <nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation">
        ${navLinksMobile}
    </nav>`;
}


/* =====================================================
   BUILD FOOTER HTML
   ===================================================== */
function buildFooter() {
    const cfg = SITE_CONFIG;
    const pta = cfg.offices.pretoria;
    const jhb = cfg.offices.johannesburg;

    /* Quick Links list items */
    const quickLinksHtml = cfg.quickLinks.map(link =>
        `<li><i data-lucide="chevron-right" width="14" height="14" class="footer-icon"></i><a href="${link.href}">${link.label}</a></li>`
    ).join('\n                    ');

    /* Capabilities list items */
    const capabilitiesHtml = cfg.capabilities.map(cap =>
        `<li><i data-lucide="chevron-right" width="14" height="14" class="footer-icon"></i>${cap}</li>`
    ).join('\n                    ');

    /* Emails list items */
    const emailsHtml = cfg.contact.emails.map(email =>
        `<li>
                        <i data-lucide="mail" width="14" height="14" class="footer-icon"></i>
                        ${email}
                    </li>`
    ).join('\n                    ');

    return `
    <!-- =====================================================
         FOOTER (Auto-generated by components.js)
    ===================================================== -->
    <footer>
        <div class="footer-inner">

            <!-- Col 1: Brand -->
            <div class="footer-col footer-col--brand">
                <div class="footer-logo">
                    <img src="${cfg.company.logoSrc}" alt="Makhaswa Logo">
                    <div class="footer-logo-text">${cfg.company.name}<small>${cfg.company.legalName}</small></div>
                </div>
                <p class="footer-desc">${cfg.company.tagline}</p>
            </div>

            <!-- Col 2: Quick Links -->
            <div class="footer-col">
                <h4>Quick Links</h4>
                <ul>
                    ${quickLinksHtml}
                </ul>
            </div>

            <!-- Col 3: Capabilities -->
            <div class="footer-col">
                <h4>Capabilities</h4>
                <ul>
                    ${capabilitiesHtml}
                </ul>
            </div>

            <!-- Col 4: Contact -->
            <div class="footer-col">
                <h4>Contact Us</h4>
                <ul>
                    <!-- Locations -->
                    <li><strong>Locations</strong></li>
                    <li>
                        <i data-lucide="map-pin" width="14" height="14" class="footer-icon"></i>
                        ${pta.label}: ${pta.address}
                    </li>
                    <li>
                        <i data-lucide="map-pin" width="14" height="14" class="footer-icon"></i>
                        ${jhb.label}: ${jhb.address}
                    </li>

                    <!-- Phones -->
                    <li class="footer-contact-separator"><strong>Phone</strong></li>
                    <li>
                        <i data-lucide="phone" width="14" height="14" class="footer-icon"></i>
                        ${pta.label}: ${pta.phone}
                    </li>
                    <li>
                        <i data-lucide="phone" width="14" height="14" class="footer-icon"></i>
                        ${jhb.label}: ${jhb.phone}
                    </li>
                    <li>
                        <i data-lucide="message-square" width="14" height="14" class="footer-icon"></i>
                        WhatsApp: ${cfg.contact.whatsapp}
                    </li>

                    <!-- Emails -->
                    <li class="footer-contact-separator"><strong>Email</strong></li>
                    ${emailsHtml}
                </ul>
            </div>

            <!-- Col 5: Our Footprint (maps) -->
            <div class="footer-col footer-col--footprint">
                <h4>Our Footprint</h4>
                <div class="footer-maps">
                    <div class="map-item map-item--spaced">
                        <span class="map-title">${pta.mapLabel}</span>
                        <iframe class="footer-map"
                            src="https://maps.google.com/maps?q=${pta.mapQuery}&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            loading="lazy" title="${pta.mapTitle}" allowfullscreen="">
                        </iframe>
                    </div>
                    <div class="map-item">
                        <span class="map-title">${jhb.mapLabel}</span>
                        <iframe class="footer-map"
                            src="https://maps.google.com/maps?q=${jhb.mapQuery}&t=&z=13&ie=UTF8&iwloc=&output=embed"
                            loading="lazy" title="${jhb.mapTitle}" allowfullscreen="">
                        </iframe>
                    </div>
                </div>
            </div>

        </div>

        <div class="footer-bottom">
            <p>${cfg.company.copyright} | Developed by <a href="https://vylex.co.za" target="_blank" rel="noopener noreferrer" style="color: inherit; text-decoration: underline;">Vylex</a></p>
            <div class="footer-bottom-reg">
                <span>REG: ${cfg.company.registration}</span>
                <span>${cfg.company.bbbee}</span>
            </div>
        </div>
    </footer>`;
}


/* =====================================================
   INJECT COMPONENTS INTO THE DOM
   ===================================================== */
function injectComponents() {
    const headerSlot = document.getElementById('site-header');
    const footerSlot = document.getElementById('site-footer');

    if (headerSlot) {
        headerSlot.outerHTML = buildHeader();
    }

    if (footerSlot) {
        footerSlot.outerHTML = buildFooter();
    }
}

/* Export for app.js to call after DOMContentLoaded */
window.MakhaswaComponents = { injectComponents, SITE_CONFIG };
